# Generated by Django 5.2.8 on 2025-12-03 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_direction', models.AutoField(primary_key=True, serialize=False)),
                ('direction_nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(primary_key=True, serialize=False)),
                ('role_nom', models.CharField(max_length=255, unique=True)),
                ('description_role', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.BigIntegerField()),
                ('nom_utilisateur', models.CharField(max_length=255)),
                ('prenom_utilisateur', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('mail', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('ip_adresse', models.CharField(max_length=255)),
                ('navigateur', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id_service', models.AutoField(primary_key=True, serialize=False)),
                ('service_nom', models.CharField(max_length=255)),
                ('id_direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.direction')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='id_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.service'),
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id_valeur', models.AutoField(primary_key=True, serialize=False)),
                ('codesh', models.CharField(max_length=255)),
                ('descrip', models.CharField(max_length=255)),
                ('unite', models.CharField(max_length=255)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pu_fact', models.DecimalField(decimal_places=2, max_digits=19)),
                ('pu_redr', models.DecimalField(decimal_places=2, max_digits=19)),
                ('methode', models.CharField(max_length=255)),
                ('incoterm', models.CharField(max_length=255)),
                ('devise', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('ref_fact', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('details_marchandises', models.CharField(max_length=255)),
                ('poid_brut', models.DecimalField(decimal_places=2, max_digits=19)),
                ('poid_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('exportateur', models.CharField(max_length=255)),
                ('pays_destinataire', models.CharField(max_length=255)),
                ('importateur', models.CharField(max_length=255)),
                ('conditionnement', models.CharField(max_length=255)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('date_effet', models.DateField()),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueValeur',
            fields=[
                ('id_historique', models.AutoField(primary_key=True, serialize=False)),
                ('champ_modifies', models.CharField(max_length=255)),
                ('ancienne_valeur', models.CharField(max_length=255)),
                ('nouvelle_valeur', models.CharField(max_length=255)),
                ('date_modif', models.DateTimeField(auto_now_add=True)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_valeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valeur')),
            ],
        ),
        migrations.CreateModel(
            name='ValeurExtrait',
            fields=[
                ('id_extraction', models.AutoField(primary_key=True, serialize=False)),
                ('date_extraction', models.DateField()),
                ('serdau', models.CharField(max_length=255)),
                ('datedau', models.DateField()),
                ('liquide', models.CharField(max_length=255)),
                ('dateliquide', models.DateField()),
                ('importateur', models.CharField(max_length=255)),
                ('exportateur', models.CharField(max_length=255)),
                ('pays_destinataire', models.CharField(max_length=255)),
                ('description_article', models.CharField(max_length=255)),
                ('poid_brut', models.DecimalField(decimal_places=2, max_digits=19)),
                ('poid_net', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=19)),
                ('unite', models.CharField(max_length=255)),
                ('prix_article', models.DecimalField(decimal_places=2, max_digits=19)),
                ('incoterm', models.CharField(max_length=255)),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='valeur',
            name='id_extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.valeurextrait'),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id_validation', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=255)),
                ('date_validation', models.DateField(blank=True, null=True)),
                ('id_extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.valeurextrait')),
                ('id_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
