# Generated by Django 6.0.1 on 2026-01-17 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valeurextrait',
            old_name='id_extraction',
            new_name='id_valeur_extrait',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='codesh',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='date_extraction',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='datedau',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='dateliquide',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='description_article',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='exportateur',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='id_utilisateur',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='importateur',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='incoterm',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='liquide',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='pays_destinataire',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='poid_brut',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='poid_net',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='prix_article',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='quantite',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='serdau',
        ),
        migrations.RemoveField(
            model_name='valeurextrait',
            name='unite',
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='codesh_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='conditionnement_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='date_ajout_extrait',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='date_effet_extrait',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='descrip_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='details_marchandises_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='devise_extrait',
            field=models.CharField(blank=True, default='USD', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='exportateur_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='id_utilisateur_extrait',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='image_extrait',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='valeur/'),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='importateur_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='incoterm_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='methode_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='pays_destinataire_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='poid_brut_extrait',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='poid_net_extrait',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='pu_fact_extrait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='pu_redr_extrait',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='quantite_extrait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='ref_fact_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='source_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='status_extrait',
            field=models.CharField(blank=True, default='EN_ATTENTE', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valeurextrait',
            name='unite_extrait',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='valeurextrait',
            table='VALEUR_EXTRAIT',
        ),
    ]
