# Generated by Django 6.0.1 on 2026-01-18 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_extraction_valeurextrait_id_valeur_extrait_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='id_utilisateur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
