# Generated by Django 5.2.8 on 2025-12-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_valeurextrait_codesh_alter_valeur_conditionnement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='valeur/'),
        ),
    ]
