# Generated by Django 5.2.8 on 2025-12-22 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_valeur_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='codesh',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='descrip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='valeur',
            name='id_utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='valeur',
            table='VALEUR',
        ),
    ]
