# Generated by Django 6.0.1 on 2026-01-18 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_valeur_id_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurextrait',
            name='id_utilisateur_extrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
