# Generated by Django 6.0.1 on 2026-01-18 16:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_valeurextrait_id_utilisateur_extrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurextrait',
            name='date_effet_extrait',
            field=models.DateField(default=api.models.today_date),
        ),
        migrations.AlterField(
            model_name='valeurextrait',
            name='image_extrait',
            field=models.ImageField(blank=True, null=True, upload_to='valeur/'),
        ),
    ]
