# Generated by Django 5.2.8 on 2026-01-07 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_valeur_codesh_alter_valeur_descrip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaction',
            name='id_log',
        ),
        migrations.RemoveField(
            model_name='logaction',
            name='id_utilisateur',
        ),
        migrations.RemoveField(
            model_name='logaction',
            name='ip_adresse',
        ),
        migrations.RemoveField(
            model_name='logaction',
            name='navigateur',
        ),
        migrations.AddField(
            model_name='logaction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='logaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='logaction',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logaction',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='logaction',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CHANGE_PASSWORD', 'Changement mot de passe'), ('CHANGE_LOGIN', 'Changement login')], max_length=30),
        ),
    ]
