# Generated by Django 5.2.8 on 2026-01-15 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_logaction_user_login_alter_logaction_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeur',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
