# Generated by Django 5.2.8 on 2026-01-15 09:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_valeur_date_ajout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeur',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
