# Generated by Django 5.2.8 on 2026-01-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_logaction_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logaction',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Connexion'), ('VISIT', 'Visite page'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('CHANGE_PASSWORD', 'Changement mot de passe'), ('CHANGE_LOGIN', 'Changement login')], max_length=30),
        ),
    ]
